name: tx_dropdown_menu
description: A flutter package with a custom drop-down menu that supports iOS and Android.
version: 0.0.1
homepage: https://github.com/Tuanxu5/tx-dropdown-menu

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
